# Generated by Django 5.2 on 2025-10-25 02:08

import django.core.validators
import django.db.models.deletion
import habitacao.models
import habitacao.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Código')),
                ('label', models.CharField(max_length=120, verbose_name='Descrição')),
                ('required', models.BooleanField(default=False, verbose_name='Obrigatório')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'db_table': 'document_types',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='PriorityCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Código')),
                ('label', models.CharField(max_length=160, verbose_name='Descrição')),
                ('group_tag', models.CharField(blank=True, help_text='Ex: social, saúde, vulnerabilidade', max_length=40, null=True, verbose_name='Grupo')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Critério de Priorização',
                'verbose_name_plural': 'Critérios de Priorização',
                'db_table': 'priority_criteria',
                'ordering': ['group_tag', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SocialBenefitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Código')),
                ('label', models.CharField(max_length=120, verbose_name='Descrição')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Benefício Social',
                'verbose_name_plural': 'Tipos de Benefícios Sociais',
                'db_table': 'social_benefit_types',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibge_code', models.CharField(max_length=7, unique=True, verbose_name='Código IBGE')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
                'db_table': 'municipalities',
                'ordering': ['uf', 'name'],
                'indexes': [models.Index(fields=['uf', 'name'], name='municipalit_uf_867871_idx')],
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_number', models.CharField(blank=True, help_text='Gerado automaticamente ao submeter (ex: AAAA-MM-XXXXXX)', max_length=32, null=True, unique=True, verbose_name='Número de Protocolo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('full_name', models.CharField(max_length=160, verbose_name='Nome Completo')),
                ('cpf', models.CharField(help_text='Formato: 000.000.000-00', max_length=14, unique=True, validators=[habitacao.validators.validate_cpf], verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=32, verbose_name='RG')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('marital_status', models.CharField(blank=True, choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('UNIAO_ESTAVEL', 'União Estável'), ('VIUVO', 'Viúvo(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('SEPARADO', 'Separado(a)'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Estado Civil')),
                ('phone_primary', models.CharField(blank=True, max_length=20, validators=[habitacao.validators.validate_phone], verbose_name='Telefone Principal')),
                ('phone_secondary', models.CharField(blank=True, max_length=20, validators=[habitacao.validators.validate_phone], verbose_name='Telefone Secundário')),
                ('email', models.EmailField(blank=True, max_length=160, verbose_name='E-mail')),
                ('address_line', models.CharField(blank=True, max_length=160, verbose_name='Logradouro')),
                ('address_number', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('address_complement', models.CharField(blank=True, max_length=60, verbose_name='Complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=80, verbose_name='Bairro')),
                ('cep', models.CharField(blank=True, help_text='Formato: 00000-000', max_length=9, validators=[habitacao.validators.validate_cep], verbose_name='CEP')),
                ('uf', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('spouse_name', models.CharField(blank=True, max_length=160, verbose_name='Nome do Cônjuge')),
                ('spouse_rg', models.CharField(blank=True, max_length=32, verbose_name='RG do Cônjuge')),
                ('spouse_birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento do Cônjuge')),
                ('main_occupation', models.CharField(blank=True, max_length=120, verbose_name='Ocupação Principal')),
                ('gross_family_income', models.DecimalField(blank=True, decimal_places=2, help_text='Renda familiar mensal bruta em R$', max_digits=12, null=True, validators=[habitacao.validators.validate_positive_income], verbose_name='Renda Familiar Bruta')),
                ('has_cadunico', models.BooleanField(default=False, verbose_name='Possui CadÚnico')),
                ('nis_number', models.CharField(blank=True, help_text='Quando possui CadÚnico', max_length=20, null=True, unique=True, validators=[habitacao.validators.validate_nis], verbose_name='Número NIS')),
                ('family_size', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Tamanho da Família')),
                ('has_elderly', models.BooleanField(default=False, verbose_name='Possui Idosos')),
                ('elderly_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade de Idosos')),
                ('has_children', models.BooleanField(default=False, verbose_name='Possui Crianças')),
                ('children_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade de Crianças')),
                ('has_disability_or_tea', models.BooleanField(default=False, verbose_name='Possui PcD ou TEA')),
                ('disability_or_tea_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade PcD/TEA')),
                ('household_head_gender', models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino'), ('OUTRO', 'Outro'), ('NAO_INFORMADO', 'Não informado')], max_length=20, verbose_name='Gênero do Chefe da Família')),
                ('family_in_cadunico_updated', models.BooleanField(default=False, verbose_name='Família no CadÚnico Atualizada')),
                ('no_own_house', models.BooleanField(default=False, verbose_name='Não possui casa própria')),
                ('precarious_own_house', models.BooleanField(default=False, verbose_name='Casa própria precária')),
                ('cohabitation', models.BooleanField(default=False, verbose_name='Coabitação')),
                ('improvised_dwelling', models.BooleanField(default=False, verbose_name='Moradia improvisada')),
                ('pays_rent', models.BooleanField(default=False, verbose_name='Paga aluguel')),
                ('rent_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[habitacao.validators.validate_positive_income], verbose_name='Valor do Aluguel')),
                ('other_housing_desc', models.CharField(blank=True, max_length=200, verbose_name='Outra Situação Habitacional')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('SUBMITTED', 'Submetida'), ('UNDER_REVIEW', 'Em Análise'), ('CORRECTION_REQUESTED', 'Correção Solicitada'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Rejeitada')], default='DRAFT', max_length=30, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submetido em')),
                ('last_review_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Revisão em')),
                ('last_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaries_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Última Revisão por')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaries_submitted', to=settings.AUTH_USER_MODEL, verbose_name='Submetido por')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='habitacao.municipality', verbose_name='Município')),
            ],
            options={
                'verbose_name': 'Beneficiário',
                'verbose_name_plural': 'Beneficiários',
                'db_table': 'beneficiaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to='habitacao.beneficiary', verbose_name='Beneficiário')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacao.prioritycriteria', verbose_name='Critério')),
            ],
            options={
                'verbose_name': 'Prioridade do Beneficiário',
                'verbose_name_plural': 'Prioridades dos Beneficiários',
                'db_table': 'beneficiary_priority',
            },
        ),
        migrations.CreateModel(
            name='SearchAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=400, verbose_name='Consulta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Auditoria de Busca',
                'verbose_name_plural': 'Auditorias de Buscas',
                'db_table': 'search_audit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BeneficiarySocialBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_text', models.CharField(blank=True, max_length=160, verbose_name='Outro (especificar)')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_benefits', to='habitacao.beneficiary', verbose_name='Beneficiário')),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacao.socialbenefittype', verbose_name='Benefício')),
            ],
            options={
                'verbose_name': 'Benefício Social do Beneficiário',
                'verbose_name_plural': 'Benefícios Sociais dos Beneficiários',
                'db_table': 'beneficiary_social_benefits',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[habitacao.validators.validate_cpf], verbose_name='CPF')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('COORDINATOR', 'Coordenador'), ('ANALYST', 'Analista'), ('CLERK', 'Atendente')], default='ANALYST', max_length=20, verbose_name='Papel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último login')),
                ('municipality', models.ForeignKey(blank=True, help_text='Escopo de atuação do usuário, se aplicável', null=True, on_delete=django.db.models.deletion.SET_NULL, to='habitacao.municipality', verbose_name='Município de Atuação')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ApplicationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Atribuído em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_applications', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído para')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='habitacao.beneficiary', verbose_name='Beneficiário')),
            ],
            options={
                'verbose_name': 'Atribuição de Inscrição',
                'verbose_name_plural': 'Atribuições de Inscrições',
                'db_table': 'application_assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['beneficiary', 'active'], name='application_benefic_03b066_idx'), models.Index(fields=['assigned_to', 'active'], name='application_assigne_6bfb6c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMIT', 'Submeter'), ('START_REVIEW', 'Iniciar Análise'), ('REQUEST_CORRECTION', 'Solicitar Correção'), ('APPROVE', 'Aprovar'), ('REJECT', 'Rejeitar'), ('UPLOAD_DOC', 'Upload de Documento'), ('VALIDATE_DOC', 'Validar Documento'), ('NOTE', 'Adicionar Nota'), ('EDIT', 'Editar')], max_length=40, verbose_name='Ação')),
                ('from_status', models.CharField(blank=True, choices=[('DRAFT', 'Rascunho'), ('SUBMITTED', 'Submetida'), ('UNDER_REVIEW', 'Em Análise'), ('CORRECTION_REQUESTED', 'Correção Solicitada'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Rejeitada')], max_length=30, verbose_name='Status Anterior')),
                ('to_status', models.CharField(blank=True, choices=[('DRAFT', 'Rascunho'), ('SUBMITTED', 'Submetida'), ('UNDER_REVIEW', 'Em Análise'), ('CORRECTION_REQUESTED', 'Correção Solicitada'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Rejeitada')], max_length=30, verbose_name='Novo Status')),
                ('message', models.TextField(blank=True, verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_history', to='habitacao.beneficiary', verbose_name='Beneficiário')),
            ],
            options={
                'verbose_name': 'Histórico de Ação',
                'verbose_name_plural': 'Histórico de Ações',
                'db_table': 'application_actions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['beneficiary', 'created_at'], name='application_benefic_504214_idx'), models.Index(fields=['action'], name='application_action_ae2185_idx')],
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200, verbose_name='Nome do Arquivo')),
                ('file_path', models.FileField(max_length=400, upload_to=habitacao.models.beneficiary_document_path, verbose_name='Arquivo')),
                ('mime_type', models.CharField(blank=True, max_length=80, verbose_name='Tipo MIME')),
                ('size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Tamanho (bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('validated', models.BooleanField(default=False, verbose_name='Validado')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validado em')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='habitacao.beneficiary', verbose_name='Beneficiário')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='habitacao.documenttype', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Documento do Beneficiário',
                'verbose_name_plural': 'Documentos dos Beneficiários',
                'db_table': 'beneficiary_documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['beneficiary', 'document_type'], name='beneficiary_benefic_92d4d2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['cpf'], name='beneficiari_cpf_12c50b_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['municipality'], name='beneficiari_municip_90a922_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['status'], name='beneficiari_status_9ea618_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['submitted_at'], name='beneficiari_submitt_715370_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['protocol_number'], name='beneficiari_protoco_7c91a3_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiarypriority',
            index=models.Index(fields=['beneficiary', 'criteria'], name='beneficiary_benefic_117f05_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='beneficiarypriority',
            unique_together={('beneficiary', 'criteria')},
        ),
        migrations.AddIndex(
            model_name='searchaudit',
            index=models.Index(fields=['user', 'created_at'], name='search_audi_user_id_2ab77a_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiarysocialbenefit',
            index=models.Index(fields=['beneficiary', 'benefit'], name='beneficiary_benefic_737b1e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='beneficiarysocialbenefit',
            unique_together={('beneficiary', 'benefit')},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['municipality'], name='users_municip_22a67d_idx'),
        ),
    ]
