# Generated by Django 5.2.7 on 2025-10-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacao', '0002_fix_nis_empty_strings'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='has_address_proof',
            field=models.BooleanField(default=False, help_text='Conta de luz, água, telefone, etc.', verbose_name='Apresentou Comprovante de Residência'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='has_birth_certificate',
            field=models.BooleanField(default=False, help_text='Certidões de estado civil', verbose_name='Apresentou Certidão de Nascimento/Casamento'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='has_cadunico_number',
            field=models.BooleanField(default=False, help_text='Comprovante do NIS ou inscrição no CadÚnico', verbose_name='Apresentou Número NIS / CadÚnico'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='has_income_proof',
            field=models.BooleanField(default=False, help_text='Holerite, declaração, etc. (quando houver)', verbose_name='Apresentou Comprovante de Renda'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='has_rg_cpf',
            field=models.BooleanField(default=False, help_text='Documentos de identificação pessoal', verbose_name='Apresentou RG e CPF'),
        ),
    ]
