# Generated by Django 5.2.7 on 2025-10-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacao', '0003_add_documentation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='municipality_name',
            field=models.CharField(blank=True, help_text='Nome do município digitado manualmente ou via CEP', max_length=100, verbose_name='Nome do Município (texto livre)'),
        ),
    ]
