# Generated by Django 5.2 on 2025-11-03 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('habitacao', '0004_beneficiary_municipality_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(help_text='Backup caso o usuário seja deletado', max_length=254, verbose_name='Email do Usuário')),
                ('user_role', models.CharField(blank=True, max_length=20, verbose_name='Papel do Usuário')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora')),
                ('action_type', models.CharField(choices=[('CREATE', 'Criar'), ('UPDATE', 'Atualizar'), ('DELETE', 'Excluir'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Exportar'), ('APPROVE', 'Aprovar'), ('REJECT', 'Rejeitar'), ('CHANGE_STATUS', 'Alterar Status'), ('UPLOAD_DOC', 'Upload de Documento'), ('DELETE_DOC', 'Excluir Documento'), ('CHANGE_PERMISSIONS', 'Alterar Permissões'), ('PASSWORD_CHANGE', 'Alteração de Senha'), ('PASSWORD_RESET', 'Reset de Senha')], db_index=True, max_length=30, verbose_name='Tipo de Ação')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do Objeto')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='Representação do Objeto')),
                ('changes', models.JSONField(blank=True, help_text='Diff das mudanças', null=True, verbose_name='Alterações')),
                ('metadata', models.JSONField(blank=True, help_text='Informações extras', null=True, verbose_name='Metadados')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('was_successful', models.BooleanField(default=True, verbose_name='Sucesso')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Tipo de Objeto')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'user'], name='audit_logs_timesta_d733ec_idx'), models.Index(fields=['action_type', '-timestamp'], name='audit_logs_action__952b82_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_logs_content_b0ef47_idx')],
            },
        ),
        migrations.CreateModel(
            name='PermissionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('field_changed', models.CharField(help_text='Ex: role, is_active, municipality', max_length=50, verbose_name='Campo Alterado')),
                ('old_value', models.TextField(blank=True, verbose_name='Valor Anterior')),
                ('new_value', models.TextField(blank=True, verbose_name='Novo Valor')),
                ('reason', models.TextField(blank=True, verbose_name='Justificativa')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_changes_made', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_changes_received', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Alvo')),
            ],
            options={
                'verbose_name': 'Alteração de Permissão',
                'verbose_name_plural': 'Alterações de Permissões',
                'db_table': 'permission_changes',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['target_user', '-timestamp'], name='permission__target__c39a79_idx'), models.Index(fields=['-timestamp'], name='permission__timesta_9d865e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('severity', models.CharField(choices=[('INFO', 'Informação'), ('WARNING', 'Aviso'), ('ERROR', 'Erro'), ('CRITICAL', 'Crítico')], default='INFO', max_length=20, verbose_name='Severidade')),
                ('category', models.CharField(choices=[('SECURITY', 'Segurança'), ('SYSTEM', 'Sistema'), ('USER', 'Usuário'), ('DATA', 'Dados'), ('PERFORMANCE', 'Performance')], max_length=20, verbose_name='Categoria')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criada em')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadados')),
                ('action_url', models.CharField(blank=True, max_length=200, verbose_name='URL da Ação')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_read', to=settings.AUTH_USER_MODEL, verbose_name='Lida por')),
                ('target_users', models.ManyToManyField(blank=True, help_text='Vazio = todos os admins', related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuários Alvo')),
            ],
            options={
                'verbose_name': 'Notificação do Sistema',
                'verbose_name_plural': 'Notificações do Sistema',
                'db_table': 'system_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'is_read'], name='system_noti_created_daae4a_idx'), models.Index(fields=['severity', '-created_at'], name='system_noti_severit_368023_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Chave da Sessão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Última Atividade')),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('device_info', models.JSONField(blank=True, null=True, verbose_name='Informações do Dispositivo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('terminated_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminada em')),
                ('termination_reason', models.CharField(blank=True, choices=[('LOGOUT', 'Logout normal'), ('EXPIRED', 'Expirou'), ('FORCED', 'Forçada pelo admin'), ('REPLACED', 'Substituída por nova sessão')], max_length=50, verbose_name='Motivo do Término')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Sessão de Usuário',
                'verbose_name_plural': 'Sessões de Usuários',
                'db_table': 'user_sessions',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', '-last_activity'], name='user_sessio_user_id_3a59ae_idx'), models.Index(fields=['is_active', '-last_activity'], name='user_sessio_is_acti_475362_idx')],
            },
        ),
    ]
